// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _5by5_AirCraftAPI.Data;

#nullable disable

namespace _5by5_AirCraftAPI.Migrations
{
    [DbContext(typeof(_5by5_AirCraftAPIContext))]
    [Migration("20240617205206_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_5by5_AirCraftAPI.Models.AirCraft", b =>
                {
                    b.Property<string>("Rab")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("CnpjCompany")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<DateTime>("DTLastFlight")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DTRegistry")
                        .HasColumnType("datetime2");

                    b.HasKey("Rab");

                    b.ToTable("AirCraft", (string)null);
                });

            modelBuilder.Entity("_5by5_AirCraftAPI.Models.Removed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("CnpjCompany")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<DateTime>("DTLastFlight")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DTRegistry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rab")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.ToTable("Removed", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
